### ISSUE TITLE
Hidden field name

### ISSUE THREAD

**Issue by fernandoaleman** [mariohmol/paperclip-keeponvalidation#1]
On the page https://github.com/mariohmol/paperclip-keeponvalidation/blob/1bbdf735bb1c30c990588cbd94db57571f93e38b/app/views/_form.html.erb#L10 is the hidden field name supposed to be :avatar_cache or :logo_cache?

``` ruby
<div class="imagem-file-upload">Logo</div>
  <%= f.input :logo , :placeholder => 'choose your logo', :label => false %>  
  <%= f.hidden_field :avatar_cache %>
</div>
```

**Comment by mariohmol** [comment]
you are right

**Comment by fernandoaleman** [comment]
Thanks for fixing and for adding this fix for Paperclip. I was needing to use this just today so you are saving me some time. :D

**Comment by mariohmol** [comment]
thats ok.. I have a app here that sometimes user paperclip and sometimes normal uploader.. until next week i will publish code to work on both..
